### ISSUE TITLE
When

### ISSUE THREAD

**Issue by rkolovanov** [CmmSheparD/game-of-life#1]
when

**Comment by rkolovanov** [comment]
when

**Comment by G-L-X-B** [comment]
then

**Comment by G-L-X-B** [comment]
Мотивации нет, поэтому работаю над ним часа два в неделю.
Но скоро будет большой коммит, в котором изменено всё, но фич не добавлено. Просто переделка системы вывода на централизованную очередь действий. Сейчас тесчу, почему ничего не работает.
